import JSZip from 'jszip';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { code, chatId } = req.body;

  // Vercel Environment Variables থেকে বটের টোকেন রিড করবে
  const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;

  if (!BOT_TOKEN) {
    return res.status(500).json({ 
      error: 'Vercel Environment Variables-এ TELEGRAM_BOT_TOKEN সেট করা হয়নি!' 
    });
  }

  if (!chatId) {
    return res.status(400).json({ error: "Telegram User Chat ID পাওয়া যায়নি।" });
  }

  try {
    const zip = new JSZip();
    zip.file("index.html", code || "<!-- No code found -->");
    zip.file("README.txt", "Generated by Telegram Mini App via Gemini AI");

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    const formData = new FormData();
    formData.append("chat_id", chatId);
    formData.append("caption", "📦 Here is your requested Project ZIP file!");
    formData.append("document", new Blob([zipBuffer]), "project-source-code.zip");

    const tgRes = await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/sendDocument`, {
      method: "POST",
      body: formData
    });

    const result = await tgRes.json();
    if (result.ok) {
      return res.status(200).json({ success: true, message: "Zip sent to your Telegram chat!" });
    } else {
      return res.status(400).json({ success: false, error: result.description });
    }
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
